# Generated by Django 3.2.9 on 2022-03-01 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20220301_1037'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
